version: '3'
services:
  app:
    build: .
    image: fastapi-demo-app
    environment:
      AWS_REGION: local
      S3_BUCKET: test
  web:
    build: nginx
    image: fastapi-demo-web
    ports:
      - "8000:80"
    environment:
      APP_HOST: app